# Generated by Django 3.2.6 on 2021-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy'), ('OTH', 'Other')], max_length=300)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=130)),
                ('email', models.EmailField(max_length=120)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
